[package]
name = "animeroba"
version = "0.1.0"
authors = ["Emilio González <emigr2k1@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.2"
serde_json = "1.0.41"
dotenv = "0.9.0"
postgres = { version = "0.15.0", features = ["with-chrono"] }
chrono = { version = "0.4", features = ["serde"] }

[dependencies.rocket_contrib]
version = "0.4.2"
features = ["tera_templates", "postgres_pool", "mongodb_pool"]

[dependencies.serde]
version = "1.0.101"
features = ["derive"]
