[package]
name = "rocketexample"
version = "0.1.0"
authors = ["Emilio González <emigr2k1@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.2"
serde = { version = "1.0.101", features = ["derive"] }
serde_json = "1.0.41"

[dependencies.rocket_contrib]
version = "0.4.2"
features = ["tera_templates", "mongodb_pool"]
