use num_derive::{FromPrimitive, ToPrimitive};
use std::fmt;

#[derive(FromPrimitive, ToPrimitive)]
pub enum Genre {
    Action,
    Adventure,
    Races,
    SciFi,
    Comedy,
    Cyberpunk,
    Sports,
    Drama,
    Ecchi,
    Scholar,
    Fantasy,
    Gore,
    Harem,
    Horror,
    Josei,
    Wrestling,
    Magic,
    Mecha,
    Militar,
    Mistery,
    Music,
    Paradogy,
    Psychologic,
    LifeMemories,
    Seinen,
    Shojo,
    Shonen,
    Supernatural,
    Vampires,
    Yaoi,
    Yuri,
    Spacial,
    Historical,
    Samurai,
    MartialArts,
    Demons,
    Romance,
    Dementia,
    Police,
}

impl fmt::Display for Genre {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        match *self {
            Self::Action => write!(f, "Acción"),
            Self::Adventure => write!(f, "Aventura"),
            Self::Races => write!(f, "Carreras"),
            Self::SciFi => write!(f, "Ciencia ficción"),
            Self::Comedy => write!(f, "Comedia"),
            Self::Cyberpunk => write!(f, "Cyberpunk"),
            Self::Sports => write!(f, "Deportes"),
            Self::Drama => write!(f, "Drama"),
            Self::Ecchi => write!(f, "Ecchi"),
            Self::Scholar => write!(f, "Escolar"),
            Self::Fantasy => write!(f, "Fantasía"),
            Self::Gore => write!(f, "Gore"),
            Self::Harem => write!(f, "Harem"),
            Self::Horror => write!(f, "Horror"),
            Self::Josei => write!(f, "Josei"),
            Self::Wrestling => write!(f, "Luchas"),
            Self::Magic => write!(f, "Magia"),
            Self::Mecha => write!(f, "Mecha"),
            Self::Militar => write!(f, "Militar"),
            Self::Mistery => write!(f, "Misterio"),
            Self::Music => write!(f, "Musica"),
            Self::Paradogy => write!(f, "Paradojas"),
            Self::Psychologic => write!(f, "Psicológico"),
            Self::LifeMemories => write!(f, "Recuerdos de la vida"),
            Self::Seinen => write!(f, "Seinen"),
            Self::Shojo => write!(f, "Shojo"),
            Self::Shonen => write!(f, "Shonen"),
            Self::Supernatural => write!(f, "Sobrenatural"),
            Self::Vampires => write!(f, "Vampiros"),
            Self::Yaoi => write!(f, "Yaoi"),
            Self::Yuri => write!(f, "Yuri"),
            Self::Spacial => write!(f, "Espacial"),
            Self::Historical => write!(f, "Histórico"),
            Self::Samurai => write!(f, "Samurai"),
            Self::MartialArts => write!(f, "Artes marciales"),
            Self::Demons => write!(f, "Demonios"),
            Self::Romance => write!(f, "Romance"),
            Self::Dementia => write!(f, "Demencia"),
            Self::Police => write!(f, "Policial"),
        }
    }
}
